global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "node_services"
    static_configs:
      - targets:
          - fb-collector:3000
          - ttk-collector:3000
          - reporter:3000
          - gateway:3000
